background_b: 255
background_g: 86
background_r: 150
rosdistro: 'hydro

  '
roslaunch:
  uris: {host_robotuna__54066: 'http://robotuna:54066/'}
rosversion: '1.10.11

  '
run_id: 6dcfa0f4-48cc-11e4-8175-b8ca3ab4b77e
